### PR TITLE
set nx_global and ny_global == 0

### PR DESCRIPTION
**Pull request by jedwards4b**
## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Initialize NX_GLOBAL and NY_GLOBAL for SCAM case
- [X] Developer(s): 
    Jim Edwards
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
      SMS_D_Ln9.T42_T42.FSCAM.derecho_intel.cam-outfrq9s
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please document the changes in detail, including _why_ the changes are made.  This will become part of the PR commit log.

The CMEPS mediator needs the global_nx and global_ny field from each active component, they were not being set by cice for the scam case.

### CODE REVIEW

**Review by dabail10 — APPROVED** [review]
Looks reasonable. Can these be merged after the git-fleximod stuff?

**Comment by jedwards4b** [comment]
Yes, that would be fine.

**Comment by jedwards4b** [comment]
@dabail10 it looks like your macos test needs an update - the error has nothing to do with my change.

**Comment by dabail10** [comment]
Here is a silly question. Where is that file?

**Comment by jedwards4b** [comment]
https://github.com/ESCOMP/CICE/blob/main/.github/workflows/test-cice.yml

**Comment by dabail10** [comment]
Got it. There was a fix to the github actions workflow that Tony added a couple weeks ago. I have updated CICE main and I will add it to cesm_cice6_4_0_10.

**Pull request closed without merging**
