### PR TITLE
reduce orbital parameters output to log

### PR DESCRIPTION
**Pull request by jedwards4b**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Reduces the printing of Orbital parameters to the ice.log file in cesm
- [X] Developer(s): 
    Jim Edwards
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Test 
- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [x] Please document the changes in detail, including _why_ the changes are made.  This will become part of the PR commit log.
The orbital parameters were being printed every timestep and created an unreadable ice.log file.  This PR reduces the print of orbital parameters to once each orbital year.

### CODE REVIEW

**Review by dabail10 — APPROVED** [review]

**Comment by jedwards4b** [comment]
@dabail10 I have one more update coming before you merge...

**Comment by jedwards4b** [comment]
@dabail10 Okay - this is ready.  I tested in PFS_P5376.ne30pg3_ne30pg3_mg17.FMTHIST.derecho_intel

**Review by dabail10 — APPROVED** [review]

**Comment by dabail10** [comment]
Sorry, these should have gone to the consortium first. I need to revert them to fix main. I will save the hash.

**Comment by jedwards4b** [comment]
These are specific to the nuopc interface and only used by cesm so I'm not sure why they need to go through the consortium?

**Comment by dabail10** [comment]
A couple reasons. The NUOPC / CMEPS cap is used by other groups (NOAA / UFS and the Australian ACCESS-NRI group). Also, this cap is under cicecore/drivers which is maintained by the Consortium.

**Pull request merged**
