### PR TITLE
Wrt restart at end

### PR DESCRIPTION
**Pull request by jedwards4b**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
    Add timestamps to rpointer files for cesm and make sure that write_restart_at_endofrun is working
- [X] Developer(s): 
    Jim Edwards
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
    Tested with cesm beta test suite

- How much do the PR code changes differ from the unmodified code? 
    - [X] bit for bit
    - [ ] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [ ] Yes
    - [X] No
- Does this PR update the Icepack submodule?  If so, the Icepack submodule must point to a hash on Icepack's main branch.
    - [ ] Yes
    - [X] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [ ] Yes
        - [X] No 
- [X] Please document the changes in detail, including _why_ the changes are made.  This will become part of the PR commit log.
A timestamp is added to the rpointer filename to improve interactions with restart files in cesm.  CESM has also added a write_restart_at_endofrun option, this PR makes sure that that flag works with the cice component.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
@jedwards4b There was PR https://github.com/CICE-Consortium/CICE/pull/969 which allowed UFS to utilize the ``write_restart_at_endofrun`` attribute. Does this provide the same or different functionality?

**Comment by dabail10** [comment]
I had updated the ESCOMP branch with the EMC changes. I guess these are still not working for us.

**Comment by jedwards4b** [comment]
@DeniseWorthen that's correct, that change was not working in cesm - I'm hoping that none of the additional changes I've made will adversely affect UFS.

**Comment by DeniseWorthen** [comment]
Hm, so it seems like if ``stop_n`` is present (and set to the end of the run) and ``write_restart_at_endofrun`` is true, we'd have a conflict between two options both trying to do the same thing and possibly two restarts trying to be written. I know one reason we wanted the endofrun option is because our "ends" don't always end on an interval.

**Comment by jedwards4b** [comment]
I don't think that there is a conflict - let me know if you see one and I'll address it.

**Comment by dabail10** [comment]
I'm also very confused here. I need to checkout this branch and test it myself. In CESM we have:

REST_OPTION, STOP_OPTION, REST_N, and STOP_N

by default, the CESM setup sets these equal. However, I guess there is a use case when they are not equal and RESTART_OPTION is say nyears, but STOP_OPTION is nmonths? I understand Denise's case when the run stops in the middle of a year, but the restarts were set to yearly say.

**Comment by jedwards4b** [comment]
There are two cases supported here.  One is setting the REST_OPTION='end' to request a restart at the end of run (only at the end of run).   And the other is to write a restart at the end of run even if that time is not a multiple of the restart write frequency as in the example @dabail10 provided.

**Comment by dabail10** [comment]
Ok. I understand. Sorry, but this has to go through the Consortium. I am happy to issue the PR there.

**Comment by DeniseWorthen** [comment]
It looks like the changes in ``ice_comp_nuopc`` only show up as differences because the two blocks (stop_alarm and restart_alarm) are switched.

**Review by dabail10 — APPROVED** [review]

**Pull request merged**
