### PR TITLE
Update to latest CICE master

### PR DESCRIPTION
**Pull request by dabail10**
For detailed information about submitting Pull Requests (PRs) to the CICE-Consortium,
please refer to: <https://github.com/CICE-Consortium/About-Us/wiki/Resource-Index#information-for-developers>

## PR checklist
- [X] Short (1 sentence) summary of your PR: 
I have updated the NUOPC cap to the latest CICE master here.
- [X] Developer(s): 
dabail10 (D. Bailey)
- [X] Suggest PR reviewers from list in the column to the right.
- [X] Please copy the PR test results link or provide a summary of testing completed below.
I have tested this in a DTEST compset. 
- How much do the PR code changes differ from the unmodified code? 
    - [ ] bit for bit
    - [X] different at roundoff level
    - [ ] more substantial 
- Does this PR create or have dependencies on Icepack or any other models?
    - [X] Yes
    - [ ] No
- Does this PR add any new test cases?
    - [ ] Yes
    - [X] No
- Is the documentation being updated? ("Documentation" includes information on the wiki or in the .rst files from doc/source/, which are used to create the online technical docs at https://readthedocs.org/projects/cice-consortium-cice/. A test build of the technical docs will be performed as part of the PR testing.)
    - [ ] Yes
    - [X] No, does the documentation need to be updated at a later time?
        - [X] Yes
        - [ ] No 
- [X] Please provide any additional information or relevant details below:

There are a lot of files changed here and there are some answer changes coming in from CICE Master. Mainly, I just need you to check the NUOPC cap to make sure I have not messed something up that impacts the UFS.

### CODE REVIEW

**Comment by DeniseWorthen** [comment]
This merge will will match what I am proposing to merge into the emc/develop branch for our switch to cice6 from cice5 with the exception of the ice_import_export.F90. 

I did the merge locally (git checkout nuopc; git merge origin/nuopc2). The changes to ice_import_export are missing.

**Comment by dabail10** [comment]
Good catch. Apparently the merge was not smart enough to pick these up. I will fix this.

**Comment by DeniseWorthen** [comment]
Great. Just a followup---we got the OK from the coupling group to replace cice5 w/ cice6 in ufs-s2s. Not sure when it will happen, but should be soon.

**Comment by dabail10** [comment]
I fixed ice_import_export.F90 I believe. Have a look now.

**Comment by DeniseWorthen** [comment]
Yes, looks good now.

**Comment by dabail10** [comment]
Great. I will go ahead and merge this into nuopc. Looks like Ben is fine with this.

**Pull request merged**
